# Generated by Django 4.2.1 on 2023-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('log_file', models.CharField(max_length=255)),
                ('start_execution', models.DateTimeField(auto_now_add=True)),
                ('end_execution', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
