# Generated by Django 4.2.2 on 2023-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200)),
                ('execution_time', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('output_file', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CommandExecution',
        ),
    ]
