# Generated by Django 4.2.2 on 2023-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0004_alter_response_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
