# Generated by Django 4.2.2 on 2023-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0005_alter_response_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
