# Generated by Django 4.2.2 on 2023-07-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0009_alter_response_end_time_alter_response_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStatusChange',
            fields=[
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='commandTool.response')),
                ('old_status', models.IntegerField()),
                ('new_status', models.IntegerField()),
                ('change_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
