# Generated by Django 4.2.2 on 2023-07-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0010_processstatuschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessStatusChange',
        ),
    ]
