# Generated by Django 4.2.2 on 2023-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0011_delete_processstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='thread',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
