# Generated by Django 4.2.2 on 2023-07-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0012_response_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='thread',
            new_name='thread_ID',
        ),
    ]
