# Generated by Django 4.2.4 on 2023-08-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandTool', '0023_alter_repo_architectures_alter_repo_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='mirrorType',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
